extends Node

enum  DoorIdx{
	BEDROOM = 1,
	ELEVATOR_FOURTH_RIGHT = 2,
	ELEVATOR_FOURTH_LEFT,
	ELEVATOR_THRID_RIGHT,
	ELEVATOR_THRID_LEFT,
	ELEVATOR_SECOND_RIGHT,
	ELEVATOR_SECOND_LEFT,
	ELEVATOR_FIRST_RIGHT,
	ELEVATOR_FIRST_LEFT,
}
enum EmoType{
	DEFAULT = 0,
	AMAZED = 1,
	QUERY = 2,
}
var elevator_current_floor = 4

var input_lock = false
